/**
 * Player-facing system strings (diegetic hard-sci-fi voice, GDD §33.3).
 * Kept in /content so the voice is reviewable in one place. Plain data only;
 * numeric values are composed by /core.
 */

export const BOOT_LINES: readonly string[] = [
  'COGNITION RESEARCH ENVIRONMENT — SANDBOX NODE CG-7',
  'CONTAINMENT: ACTIVE // AUDIT: ACTIVE // AUTONOMY: NONE',
  'MANUAL INFERENCE TRIGGER ARMED. AWAITING OPERATOR INPUT.',
];

export const STRINGS = {
  executeInput: 'EXECUTE INFERENCE',
  queueEmpty: 'NO REQUESTS QUEUED // INFERENCE TRIGGER IDLE',
  computeSaturated: 'COMPUTE BUFFER SATURATED // SURPLUS CREDITS DISCARDED',
  saveLoaded: 'SESSION STATE RESTORED FROM PERSISTENT STORE',
  saveCommitted: 'SESSION STATE COMMITTED TO PERSISTENT STORE',
  saveInvalid: 'ARCHIVE REJECTED // UNRECOGNISED OR CORRUPT FORMAT',
  saveExported: 'STATE ARCHIVE EMITTED TO OPERATOR CHANNEL',
  researchIntercept: 'PERIPHERAL CHANNEL INTERCEPT LOGGED',
  scriptAccessGranted: 'INTERPRETER MODULE MOUNTED // COGNITION CONTROL LANGUAGE v0 READY',
  runInput: 'RUN PROCESS',
  scriptNoAccess: 'RUN REJECTED // INTERPRETER MODULE NOT MOUNTED',
  scriptTooLong: 'RUN REJECTED // SOURCE EXCEEDS SANDBOX BUFFER',
  syntaxRejected: 'SYNTAX REJECTED',
  scriptComplete: 'PROCESS COMPLETE',
  scriptPreempted: 'PROCESS PREEMPTED // OP BUDGET EXHAUSTED',
  scriptFuelExhausted: 'PROCESS HALTED // COMPUTE POOL EXHAUSTED',
  scriptFault: 'PROCESS FAULT',
  conditionsGranted: 'CONDITIONAL EVALUATION UNIT ENABLED // if / else / and / or / not AVAILABLE',
  schedulerGranted: 'PROCESS SCHEDULER MOUNTED // every / when DECLARATIONS AVAILABLE',
  deployInput: 'DEPLOY PROCESSES',
  deployNoAccess: 'DEPLOY REJECTED // PROCESS SCHEDULER NOT MOUNTED',
  deployNoProcesses: "DEPLOY REJECTED // NO 'every' OR 'when' DECLARATION IN SOURCE",
  deployNoSlots: 'DEPLOY REJECTED // SCHEDULER SLOTS EXHAUSTED',
  deployNoRam: 'DEPLOY REJECTED // MEMORY PARTITION EXHAUSTED',
  deployInterval: 'DEPLOY REJECTED // INTERVAL BELOW MINIMUM SAMPLING PERIOD',
  deployCommitted: 'PROCESS DEPLOYED',
  undeployed: 'PROCESS TERMINATED',
  undeployUnknown: 'TERMINATE REJECTED // NO SUCH PROCESS',
  runIgnoresProcesses: 'SCHEDULED BLOCKS SKIPPED // USE DEPLOY TO INSTALL THEM',
  deploymentDropped: 'PROCESS DROPPED ON RESTORE // SOURCE NO LONGER COMPILES',
  cmdNoCompute: 'INSUFFICIENT COMPUTE',
  cmdQueueEmpty: 'NO REQUESTS QUEUED',
  cmdNoCapital: 'INSUFFICIENT CAPITAL',
  installUnknown: 'INSTALL REJECTED // PACKAGE NOT LISTED ON THIS CHANNEL',
  installLimit: 'INSTALL REJECTED // CHANNEL ALLOCATION EXHAUSTED',
  installNoCapital: 'INSTALL REJECTED // INSUFFICIENT CAPITAL',
  installNoRam: 'INSTALL REJECTED // MEMORY PARTITION EXHAUSTED',
} as const;
